### ISSUE TITLE
throw "read: connection reset by peer" error ,when I use SLL Protocol.

### ISSUE THREAD

**Issue by xiaoke1256** [mholt/caddy-l4#267]
My CaddyFile like this
```
{
      layer4 {
                0.0.0.0:8883 {

                        @secure tls
                        route @secure {
                                tls {
                                }
                                proxy {
                                        upstream 171.30.0.85:1883 171.30.0.86:1883
                                }
                        }
                }
        }

}
```

the log I receive like this: 
```
"error": "writeto tcp 171.30.0.89:43420->171.30.0.85:1883: read tcp 171.30.0.89:43420->171.30.0.85:1883: read: connection reset by peer"
``` 

However, if I use single IP at "upstream" , it works.
```
{
      layer4 {
                0.0.0.0:8883 {

                        @secure tls
                        route @secure {
                                tls {
                                }
                                proxy {
                                        upstream 171.30.0.85:1883 
                                }
                        }
                }
        }
}
```
How can I do to fix it, when I use 2 IPs ?

**Comment by vnxme** [comment]
Hi! It's unclear from your description whether you would like to have 2 upstreams or 1 upstream having 2 dial addresses. What you have in the first config is the latter (each address after `upstream` is treated as a separate dial address). To opt for the former, you would have to either include 2 lines of `upstream [...]`, or use a short syntax `proxy [...] [...]` (each address is treated as a separate upstream).

**Comment by xiaoke1256** [comment]
It  worked. Thank you very much!
```
{
       layer4 {
                0.0.0.0:8883 {

                        @secure tls
                        route @secure {
                                tls {
                                }
                                proxy {
                                        upstream 171.30.0.85:1883
                                        upstream 171.30.0.86:1883
                                }
                        }
                }
        }
}
```

**Comment by xiaoke1256** [comment]
What's the difference between "2 line of `upstream [...]`" and "1 upstream with 2 dial addresses"?

**Comment by francislavoie** [comment]
No difference, they just get merged together. Just preference in config style.

**Comment by xiaoke1256** [comment]
@vnxme Can you resolve my confusion? Thank you!

**Comment by vnxme** [comment]
The `dial` addresses inside the `upstream` option are provisioned into the `peers` inner structure in the l4proxy module, so you may track the code and see where and how they are used.

My understanding is that there is a difference between these two variants:
- the `max_connections` option of the `upstream` is applied to each `dial` address, so that an upstream with 2 dial addresses may have twice as many connections as an upstream with 1 dial address;
- the `proxy` handler tries all upstreams seqentially, i.e. the second one **if and only if** the first one has failed;
- at the same time the `proxy` handler connects to all `dial` addresses of a single `upstream` **simultaneously**, i.e. returns an error if any dial address is inaccessible.

I remember @mholt [described](https://github.com/mholt/caddy-l4/pull/217#issuecomment-2234046221) the exact purpose of multiple dial addresses in reply to my statement contrasting the `proxy` handler here with the `reverse_proxy` option in the mainline code:

>> I'm not sure why such a difference exists and what the use of multiple addresses per single upstream is
>
>This is a really cool feature IMO! Even if niche. I actually used something like this with a backup service I wrote years ago. The basic idea is that you can have one downstream client that is able to communicate with multiple identical upstreams simultaneously. One upload to the proxy, then it tees to multiple upstreams, and their outputs all get aggregated to the client. This requires special handling by the client and the servers have to be in the same state (meaning, they have to be in a state where one will error and the others don't, for example, to avoid breaking your business logic) -- but it is quite useful in some cases. I think we can even improve on how this situation is handled and make more things configurable, but I digress; that's a discussion for another day.

Thus, I would recommend the users to always define **one** `dial` address per each `upstream` option of the `proxy` handler, unless they are certain they need more addresses and understand all the implications such a config may have taking into account the way multiple `dial` addresses are treated in the code.

**Comment by mholt** [comment]
Yep, it can be handy to have a cluster of backends that act as one sometimes; but it's niche.
