### ISSUE TITLE
Listen on domain

### ISSUE THREAD

**Issue by FandaOG** [mholt/caddy-l4#36]
Hi,
I'd like to use Caddy as proxy for multiple MySQL server and others services in one server. I want to use same standard port 3306. The idea is use domains to decide which port should be used (1st MySQL 9006, 2nd MySQL 9007 etc.). I tried this config.json, but I've got an error  `run: loading initial config: loading new config: layer4 app module: start: listen tcp 10.255.254.17:13222: bind: cannot assign requested address`

Do you have an idea how to fix it? Thanks.

```
{
  "apps": {
    "layer4": {
      "servers": {
        "mysql-dev": {
          "listen": [
            "mysql-dev.mydomain.com:3306"
          ],
          "routes": [
            {
              "handle": [
                {
                  "handler": "proxy",
                  "upstreams": [
                    {
                      "dial": [
                        "10.0.0.40:9006"
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        "mysql-test": {
          "listen": [
            "mysql-test.mydomain.com:3306"
          ],
          "routes": [
            {
              "handle": [
                {
                  "handler": "proxy",
                  "upstreams": [
                    {
                      "dial": [
                        "10.0.0.40:9007"
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

**Comment by francislavoie** [comment]
Unfortunately, what you're trying won't be possible.

For Caddy to know which domain the request was for, the client has to have sent the domain in the data payload sent along. With HTTP, that's done via the `Host` header. With HTTPS, that's done via TLS-SNI (Server Name Identification - a field in the TLS handshake that has the hostname).

With MySQL, there's no such standard for sending along a domain, so Caddy will never actually know the domain.

The only way you could do this is by using different ports instead of hostnames, or different IP addresses (by having more than one network adapter).

The error you're getting is because you're trying to bind twice on port 3306, which doesn't work. Only a single server can bind to the same port at a time, otherwise there would be no way to disambiguate where the TCP packets should go (that's the reason ports exist, for routing traffic to specific applications).

**Comment by ThisIsTenou** [comment]
I want to add that mysql supports DNS SRV records. This might help you keep it neat and tidy, taking away the necessity to append the specific port to your config in your mysql-client should you go with the approach of using different ports, as suggested by Francis.

**Comment by mholt** [comment]
`bind: cannot assign requested address` means that the system wasn't able to bind to a socket on the address, in this case `10.255.254.17:13222` - i.e. your DNS resolver resolved the domain to that IP address, and the system isn't able to bind to that socket.
