### ISSUE TITLE
Does the module support RTMP?

### ISSUE THREAD

**Issue by toby3d** [mholt/caddy-l4#8]
I am using a docker with an RTMP server and I want to route requests on `rtmp://example.com:1935/live` to docker `172.15.0.1:1935`.

Can I do this with this module and if so, what should be the configuration?

**Comment by mholt** [comment]
I am not familiar with RTMP, but it looks like it uses TCP and, optionally, TLS.

So yes, this module supports it since it operates over TCP (layer 4). This module doesn't care about the protocols that are implemented above the TCP layer. When used as a proxy, for example, it will transparently shuttle all the bytes over the wire, without any interpretation.

As far as this: `rtmp://example.com:1935/live` -- I am not familiar enough with the protocol to know what this means. It looks HTTP-esque; does it actually operate over HTTP?

Anyway, here's a simple TCP proxy config. The README has more examples.

```json
{
	"apps": {
		"layer4": {
			"servers": {
				"example": {
					"listen": [":1935"],
					"routes": [
						{
							"handle": [
								{
									"handler": "proxy",
									"upstreams": [
										{"dial": ["172.15.0.1:1935"]}
									]
								}
							]
						}
					]
				}
			}
		}
	}
}
```
